import "@/styles/globals.css";
import "@radix-ui/themes/styles.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { cookies } from "next/headers";
import { TRPCReactProvider } from "@/trpc/react";
import { Theme } from "@radix-ui/themes";
import NavBar from "@/components/layout/navbar";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gradient-to-br from-background via-indigo-500 to-purple-500 font-Roboto">
        <Theme accentColor="iris" grayColor="sand" radius="full" scaling="95%">
          <TRPCReactProvider cookies={cookies().toString()}>
            <NavBar />
            <hr className="mx-24 rounded-full border-[1px] border-indigo-700" />
            {children}
          </TRPCReactProvider>
        </Theme>
      </body>
    </html>
  );
}
