import "@/styles/globals.css";
import "@radix-ui/themes/styles.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { cookies } from "next/headers";
import { TRPCReactProvider } from "@/trpc/react";
import { Theme } from "@radix-ui/themes";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className=" font-Roboto">
        <Theme accentColor="iris" grayColor="sand" radius="full" scaling="95%">
          <TRPCReactProvider cookies={cookies().toString()}>
            {children}
          </TRPCReactProvider>
        </Theme>
      </body>
    </html>
  );
}
